### ISSUE TITLE
Button shortcode cannot be embedded inside a table

### ISSUE THREAD

**Issue by wonboyn** [marketempower/axiom#13]
Hi there,

I was trying to use the button shortcode in a table as follows:

| Organisation | |
| --- | --- |
| Company A | {{< button type="info" text="Website" href="http://some.url" >}} |
| Company B | Blah blah blah |

When rendered, the table excludes anything from the start of the shortcode on & the remaining table markdown gets treated as a string.

**Comment by jhauraw** [comment]
This won't work, too much shortcode nesting.
