### ISSUE TITLE
Using Font Awesome svg icons

### ISSUE THREAD

**Issue by wonboyn** [marketempower/axiom#14]
Hi again,

I would like to use some of the Font Awesome icons. 
I tried to follow your instructions for adding extra svg images but haven't been able to get it working as expected.
The steps I followed were:
* download the free release zip from the Font Awesome GitHub repo
* extract the svg's I wanted into {site}/layout/partials/svg
* edit each svg to add the markup: 

`{{ with .class }}class="{{ . }}" {{ end }}{{ with .style }}style="{{ . | safeCSS }}" {{ end }}viewBox="{{ with .viewbox }}{{ . }}{{ else }}0 0 32 32{{ end }}" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"`

With this I can get the font awesome icon to display using the svg shortcode.
But cannot get the icon to be the size of any of the included svg images.

Any suggestions would be greatly appreciated.

Thanks

Tim

**Comment by jhauraw** [comment]
You have to use the icon's original size instead of `32 32`. Use an SVG viewer or inspect and FA icon to see what the original viewbox is.
