### ISSUE TITLE
Tag Cloud Settings?

### ISSUE THREAD

**Issue by krionical** [marketempower/axiom#18]
The default site has some tags listed on the homepage which read as hugo, axiom and jamstack on the homepage. Where is the code to change these default tags located?

**Comment by jhauraw** [comment]
No where. Tag clouds are generated from Content:
https://github.com/marketempower/axiom-example/blob/master/content/posts/example-post-1.md

**Comment by krionical** [comment]
Thanks. That solved the issue. I had placed the example posts in a folder outside of posts, and assumed the tags would not be picked up in the example posts since the content was no longer being displayed in the feed. That assumption turned out to be wrong so deleting the content tags in the new example folder outside of posts fixed the problem.
