### ISSUE TITLE
CC-BY-SA-4.0 infects content

### ISSUE THREAD

**Issue by keithyipkw** [marketempower/axiom#28]
Is it intended to force user-written content to be shared under the same license?

Generated static websites using Axiom is a transformation/derivative of the source code. Share-alike requires the whole websites to be shared under the same license. CC-BY-SA-4.0 prohibits website visitors to adapt the content in their work or else, it infects their work. This problem can be solved by the users dual-licensing the content with some lessor licenses. However, the second problem cannot be solved so easily.

There are licenses incompatible with CC-BY-SA-4.0. The users cannot incorporate materials under those licenses into their website. This restricts the users from what they can write.

**Comment by jhauraw** [comment]
No the license on applies to the theme code itself, and does not pertain to user generated content.
