### ISSUE TITLE
Highlight does not take effect

### ISSUE THREAD

**Issue by changsen-dev** [marketempower/axiom#4]
Hello, I really like this, but when I updated to the latest version, there was a problem, can you help me？
The main problem is that the highlight does not take effect. The old version is ok for me. The new version has no color no matter whether I switch between **dark** or **light**. As shown in the figure below, I do n’t know where the problem is.

![WeChatWorkScreenshot_989b8b3e-b32e-4535-bcb4-564d2a8ebe9c](https://user-images.githubusercontent.com/59425847/82771291-1d192600-9e6e-11ea-8ec6-012953b15c85.png)

localhost development：
![image](https://user-images.githubusercontent.com/59425847/82771324-34f0aa00-9e6e-11ea-93f8-9b9be288eb20.png)

older version：
![image](https://user-images.githubusercontent.com/59425847/82771347-4639b680-9e6e-11ea-8c08-7f623ab9fa3a.png)

Thank You

**Comment by jhauraw** [comment]
Do you have a link to your source repository? I need to see your setup.

**Comment by changsen-dev** [comment]
This is my configuration：
...
[params]
mainSections = ["posts"]
copyrightYear = 2016
dateFormat = "Jan 2, 2006 3:04PM"
highlight = "light"
...

console log：
[changsen@cmbp axiom-example-0.2.1]$ hugo server
-------------------+--------
  Pages            |   128
  Paginator pages  |     6
  Non-page files   |     0
  Static files     |    20
  Processed images |     0
  Aliases          |    36
  Sitemaps         |     1
  Cleaned          |     0

Built in 193 ms
Watching for changes in /Users/changsen/Desktop/062/axiom-example-0.2.1/{assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /Users/changsen/Desktop/062/axiom-example-0.2.1/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

**Comment by changsen-dev** [comment]
> Do you have a link to your source repository? I need to see your setup.

No, I did it specifically. First, download example and axiom under your repository, then put axiom under the theme directory of example, and then run the hugo server

**Comment by jhauraw** [comment]
You can't update that way, you have to sync the config file settings too.

What about this part from the docs?
https://axiom-example.netlify.app/docs/configuration/

To enable Axiom's Syntax Highlighting color schemes to take effect, you will need to enable Markup Highlight Classes:

```toml
[markup]
[markup.highlight]
noClasses = false
# Optional line numbers
lineNos = false
lineNumbersInTable = false
```

**Comment by jhauraw** [comment]
Also what language code are you using in the code fence for syntax highlighting the kubernotes code? Is it one of Chroma's supported lang codes? The names are different than Prisms. The Hugo docs show the names available:
https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages

**Comment by changsen-dev** [comment]
Inline code can be highlighted, but block code is not。

In addition，If I do nothing, then roll back the version, it is ok. 

This is the website where I am running an old [version()](https://changsen.io)

![image](https://user-images.githubusercontent.com/59425847/82771997-65394800-9e70-11ea-9b31-71660ffb2971.png)

**Comment by jhauraw** [comment]
I need to see the Markdown file where the code snippet is. Can you paste or screenshot that?

Also, please confirm you have in config.toml at bottom:

```toml
[markup]
[markup.highlight]
noClasses = false
```

**Comment by changsen-dev** [comment]
> Also what language code are you using in the code fence for syntax highlighting the kubernotes code? Is it one of Chroma's supported lang codes? The names are different than Prisms. The Hugo docs show the names available:
> https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages

All Bash

![image](https://user-images.githubusercontent.com/59425847/82772296-5901ba80-9e71-11ea-9cba-23e27d8cb114.png)

**Comment by changsen-dev** [comment]
Ok, I solved it, happy, the specific approach is:
The 0.5.69 I used before, the original configuration must be effective. After I downloaded the new 0.6.x, I copied the config.toml, thinking it will definitely take effect, but no, just after repeated testing, as long as When I commented out the red box in the picture below, and then uncommented the green box, it ’s okay, maybe it ’s the difference between different versions, it ’s solved now, thank you

![image](https://user-images.githubusercontent.com/59425847/82772573-25736000-9e72-11ea-908d-944668a7730f.png)

**Comment by jhauraw** [comment]
Ok, good. The reason is `codeFences` must be set to `true` otherwise highlighting won't work. `true` is Hugo default. `codeFences = false` is from OLD config and won't work now.

Glad you are up and running and thanks for using Axiom! 👍
