### ISSUE TITLE
LinkedIn Post inspector is unable to fetch featured image

### ISSUE THREAD

**Issue by namkam5** [marketempower/axiom#8]
Featured image loads fine on facebook and twitter post inspector. linkedin seems to have issues fetching the image.

https://www.linkedin.com/post-inspector/inspect/https:%2F%2Faxiom-example.netlify.app%2Fexample-post-3%2F

Thanks for the great theme!

**Comment by jhauraw** [comment]
Hi, thank for the kind words about Axiom.

`meta og:image` works fine on real websites. LinkedIn doesn't like the `page-default.webp` image on the example for some reason. You can see it working here on production real website just fine here:

https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.jhaurawachsman.com%2Fhugo-atom-syndication-xml-template%2F

**Comment by namkam5** [comment]
Sounds great, closing this now. Thanks!
